name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  vps1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" >> ~/bash-standard-library.rsa
          chmod 600 ~/bash-standard-library.rsa

          ssh "$SSH_USER"@"$SSH_HOST" -o StrictHostKeyChecking=no -i ~/bash-standard-library.rsa <<EOF
          if [ -d /opt/lib/bash-standard-library ]; then
              cd /opt/lib/bash-standard-library
              sudo git stash
              sudo git pull
              sudo git stash pop
              cd -
          else
              cd /opt/lib
              sudo git clone https://github.com/douglasparker/bash-standard-library.git
              cd -
          fi
          EOF
